const INCH=96;
const LABEL_SIZES={POT:{widthIn:.75,heightIn:5},WRAP:{widthIn:5,heightIn:.5}};
let DEFAULT_LAYOUTS={}, labelType="POT", rows=[], filteredRows=[], currentRowIndex=0, selectedId="ITEM", layout=null;
let showSafeZone=true, showGrid=true, testMode=false;
let calibration=JSON.parse(localStorage.getItem("beinvtCalibration")||'{"scaleX":1,"scaleY":1}');
let presets=JSON.parse(localStorage.getItem("beinvtLayoutPresets")||"{}");
let queue=JSON.parse(localStorage.getItem("beinvtPrintQueue")||"[]");
let undoStack=[], redoStack=[], isRestoring=false;
const $=id=>document.getElementById(id);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const cap=s=>String(s??"").toUpperCase();
function sizePx(type=labelType){const s=LABEL_SIZES[type];return{w:Math.round(s.widthIn*INCH),h:Math.round(s.heightIn*INCH)}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function pushHistory(){if(isRestoring||!layout)return;undoStack.push(clone(layout));if(undoStack.length>100)undoStack.shift();redoStack=[];updateUndoButtons()}
function undo(){if(!undoStack.length)return;redoStack.push(clone(layout));isRestoring=true;layout=undoStack.pop();labelType=layout.labelType||labelType;isRestoring=false;saveWorkingLayout();renderAll();updateUndoButtons()}
function redo(){if(!redoStack.length)return;undoStack.push(clone(layout));isRestoring=true;layout=redoStack.pop();labelType=layout.labelType||labelType;isRestoring=false;saveWorkingLayout();renderAll();updateUndoButtons()}
function updateUndoButtons(){$("undoBtn").disabled=!undoStack.length;$("redoBtn").disabled=!redoStack.length}
async function loadDefaults(){for(const [k,u] of [["POT","layouts/pot-standard.json"],["WRAP","layouts/wrap-standard.json"]]){try{DEFAULT_LAYOUTS[k]=await (await fetch(u,{cache:"no-store"})).json()}catch(e){DEFAULT_LAYOUTS[k]=fallbackLayout(k)}}}
function fallbackLayout(t){return t==="POT"?{name:"Pot Standard",labelType:"POT",safeMarginPx:4,gridPx:4,objects:{ITEM:{x:8,y:144,w:56,h:318,rot:0,fontSize:44,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"},WO:{x:3,y:22,w:66,h:16,rot:-90,fontSize:16,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"},QR:{x:6,y:42,w:58,h:58,rot:0,locked:false,visible:true},WEEK:{x:55,y:105,w:16,h:52,rot:-90,fontSize:13,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"}}}:{name:"Wrap Standard",labelType:"WRAP",safeMarginPx:3,gridPx:4,objects:{ITEM:{x:142,y:5,w:315,h:38,rot:0,fontSize:30,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"},WO:{x:8,y:13,w:96,h:18,rot:0,fontSize:16,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"},QR:{x:104,y:4,w:40,h:40,rot:0,locked:false,visible:true},WEEK:{x:460,y:12,w:18,h:24,rot:-90,fontSize:12,fontFamily:"Times New Roman",locked:false,visible:true,alignH:"center",alignV:"middle"}}}}
function setLayout(n,keepHist=true){if(keepHist)pushHistory();layout=clone(n);labelType=layout.labelType||labelType;clampAllObjects();saveWorkingLayout();renderAll()}
function saveWorkingLayout(){localStorage.setItem("beinvtWorkingLayout_"+labelType,JSON.stringify(layout))}
function loadWorkingLayout(type){try{const s=localStorage.getItem("beinvtWorkingLayout_"+type);if(s)return JSON.parse(s)}catch(e){}return clone(DEFAULT_LAYOUTS[type]||fallbackLayout(type))}
function parseCsv(text){const out=[];let row=[],cur="",q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch=='"'){if(text[i+1]=='"'){cur+='"';i++}else q=false}else cur+=ch}else{if(ch=='"')q=true;else if(ch==","){row.push(cur);cur=""}else if(ch=="\n"){row.push(cur);out.push(row);row=[];cur=""}else if(ch!="\r")cur+=ch}}row.push(cur);out.push(row);while(out.length&&out[out.length-1].every(c=>!String(c).trim()))out.pop();return out}
async function loadCsv(){const txt=await(await fetch("data/labels.csv?cache="+Date.now())).text();const g=parseCsv(txt);if(!g.length)return;const h=g[0].map(x=>x.trim());rows=g.slice(1).map(line=>{const o={};h.forEach((k,i)=>o[k]=line[i]||"");const act=o["Activity Code"]||"",d=new Date(o["Last Updated"]||"");return{wo:o["Work Order"]||"",act,crop:o["Crop"]||"",scion:o["Scion"]||"",rootstock:o["Rootstock"]||"",tray:o["Tray Type"]||"",labelColor:o["Label Color"]||"",labelsNeeded:o["Labels Needed"]||"1",week:/initiation/i.test(act)?isoWeekText(d):""}}).filter(r=>r.wo);filteredRows=rows.slice();renderRows()}
function isoWeekText(date){if(!(date instanceof Date)||isNaN(date))return"";const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y0=new Date(Date.UTC(d.getUTCFullYear(),0,1));return"WK "+Math.ceil((((d-y0)/86400000)+1)/7)}
function currentRow(){if(testMode)return{wo:"WO9999999999",act:"INITIATION",crop:"OLIVE",scion:"SUPER LONG OLIVE VARIETY NAME THAT SHOULD AUTO FIT",rootstock:"EXTREMELY LONG ROOTSTOCK NAME FOR WORST CASE TESTING",labelsNeeded:"3",week:"WK 52"};return filteredRows[currentRowIndex]||rows[0]||{wo:"WO123456",scion:"TEST ITEM",rootstock:"TEST ROOTSTOCK",week:"WK 52",act:"INITIATION",labelsNeeded:"1"}}
function labelText(id,row){if(id==="WO")return cap(row.wo||"WO");if(id==="ITEM"){const olive=/\bolive\b/i.test(row.crop||"");return cap(olive?(row.scion||row.rootstock||"ITEM"):(row.rootstock||row.scion||"ITEM"))}if(id==="WEEK")return cap(row.week||"WEEK");return""}
function qrUrl(text){return"https://quickchart.io/qr?size=220&text="+encodeURIComponent(text||" ")}
function renderAll(){$("labelType").value=labelType;$("safeToggle").checked=showSafeZone;$("gridToggle").checked=showGrid;renderCanvas();renderObjectPanel();syncControls();renderPresetList();renderQueue();updateUndoButtons()}
function renderCanvas(){const host=$("canvasHost");host.innerHTML="";const s=sizePx(),zoom=Number($("zoom").value||1);const stage=document.createElement("div");stage.className="stageInner";stage.style.transform=`scale(${zoom})`;const lab=document.createElement("div");lab.className="label";lab.style.width=s.w+"px";lab.style.height=s.h+"px";stage.appendChild(lab);if(showGrid){const gp=Number($("gridPx").value||layout.gridPx||4);const gr=document.createElement("div");gr.className="gridOverlay";gr.style.backgroundImage=`linear-gradient(to right, rgba(2,6,23,.28) 1px, transparent 1px),linear-gradient(to bottom, rgba(2,6,23,.28) 1px, transparent 1px)`;gr.style.backgroundSize=`${gp}px ${gp}px`;lab.appendChild(gr)}if(showSafeZone){const safe=document.createElement("div");safe.className="safeZone";const m=Number(layout.safeMarginPx||0);safe.style.left=m+"px";safe.style.top=m+"px";safe.style.width=Math.max(1,s.w-2*m)+"px";safe.style.height=Math.max(1,s.h-2*m)+"px";lab.appendChild(safe)}const row=currentRow();for(const id of ["ITEM","WO","QR","WEEK"]){const o=layout.objects[id];if(!o||o.visible===false)continue;const el=document.createElement("div");el.className="obj"+(selectedId===id?" selected":"")+(o.locked?" locked":"");el.dataset.id=id;el.style.left=o.x+"px";el.style.top=o.y+"px";el.style.width=o.w+"px";el.style.height=o.h+"px";el.style.transform=`rotate(${Number(o.rot||0)}deg)`;el.style.transformOrigin="center center";if(id==="QR"){renderQrInto(el,row.wo)}else{const c=document.createElement("div");c.className="objContent";c.textContent=labelText(id,row);c.style.fontSize=(o.fontSize||16)+"px";c.style.fontFamily=`"${o.fontFamily||"Times New Roman"}", Georgia, serif`;c.style.justifyContent=alignH(o.alignH);c.style.alignItems=alignV(o.alignV);el.appendChild(c)}lab.appendChild(el);attachObjectEvents(el)}host.appendChild(stage);autoFitTextObjects()}
function renderQrInto(el,text){const img=document.createElement("img");img.src=qrUrl(text);img.alt="QR";img.onerror=function(){el.innerHTML="";const c=document.createElement("canvas");el.appendChild(c);if(window.BEINVT_QR_FALLBACK)window.BEINVT_QR_FALLBACK.draw(c,text)};el.appendChild(img)}
function alignH(v){return v==="left"?"flex-start":v==="right"?"flex-end":"center"}function alignV(v){return v==="top"?"flex-start":v==="bottom"?"flex-end":"center"}
function autoFitTextObjects(){for(const id of["ITEM","WO","WEEK"]){const e=document.querySelector(`.obj[data-id="${id}"]`),c=e&&e.querySelector(".objContent");if(!c)continue;const o=layout.objects[id];let hi=Number(o.fontSize||16),lo=6,best=lo;c.style.fontSize=hi+"px";if(c.scrollWidth<=c.clientWidth&&c.scrollHeight<=c.clientHeight)continue;while(lo<=hi){const mid=Math.floor((lo+hi)/2);c.style.fontSize=mid+"px";if(c.scrollWidth<=c.clientWidth&&c.scrollHeight<=c.clientHeight){best=mid;lo=mid+1}else hi=mid-1}c.style.fontSize=best+"px"}}
function attachObjectEvents(el){const id=el.dataset.id;el.addEventListener("pointerdown",e=>{e.stopPropagation();selectObject(id);if(layout.objects[id].locked||e.target.classList.contains("handle"))return;startMove(e,el,id)});for(const dir of["n","s","e","w","ne","nw","se","sw"]){const h=document.createElement("div");h.className="handle "+dir;h.dataset.dir=dir;h.addEventListener("pointerdown",e=>{e.stopPropagation();e.preventDefault();selectObject(id);if(layout.objects[id].locked)return;startResize(e,el,id,dir)});el.appendChild(h)}}
function labelBounds(){return sizePx()}function gridSnapVal(v){if(!$("snapGridToggle").checked)return v;const g=Number($("gridPx").value||layout.gridPx||4);return Math.round(v/g)*g}
function startMove(e,el,id){pushHistory();const o=layout.objects[id],start={x:e.clientX,y:e.clientY,ox:o.x,oy:o.y};let raf=0,last=e;function apply(ev){const z=Number($("zoom").value||1);let nx=gridSnapVal(start.ox+(ev.clientX-start.x)/z),ny=gridSnapVal(start.oy+(ev.clientY-start.y)/z);const sn=snapRect({x:nx,y:ny,w:o.w,h:o.h},id);o.x=Math.round(sn.x);o.y=Math.round(sn.y);clampObject(id);el.style.left=o.x+"px";el.style.top=o.y+"px";syncControls();drawGuides(sn.guides)}function mv(ev){last=ev;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;apply(last)})}function up(){document.removeEventListener("pointermove",mv);document.removeEventListener("pointerup",up);clearGuides();saveWorkingLayout();renderAll()}document.addEventListener("pointermove",mv);document.addEventListener("pointerup",up)}
function startResize(e,el,id,dir){pushHistory();const o=layout.objects[id],st={x:e.clientX,y:e.clientY,ox:o.x,oy:o.y,ow:o.w,oh:o.h};let raf=0,last=e;function apply(ev){const z=Number($("zoom").value||1),dx=(ev.clientX-st.x)/z,dy=(ev.clientY-st.y)/z;let x=st.ox,y=st.oy,w=st.ow,h=st.oh;if(dir.includes("e"))w=st.ow+dx;if(dir.includes("s"))h=st.oh+dy;if(dir.includes("w")){w=st.ow-dx;x=st.ox+dx}if(dir.includes("n")){h=st.oh-dy;y=st.oy+dy}w=Math.max(8,gridSnapVal(w));h=Math.max(8,gridSnapVal(h));x=gridSnapVal(x);y=gridSnapVal(y);const b=labelBounds();x=clamp(x,0,Math.max(0,b.w-w));y=clamp(y,0,Math.max(0,b.h-h));w=Math.min(w,b.w-x);h=Math.min(h,b.h-y);const sn=snapRect({x,y,w,h},id);o.x=Math.round(sn.x);o.y=Math.round(sn.y);o.w=Math.round(sn.w);o.h=Math.round(sn.h);Object.assign(el.style,{left:o.x+"px",top:o.y+"px",width:o.w+"px",height:o.h+"px"});syncControls();drawGuides(sn.guides)}function mv(ev){last=ev;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;apply(last)})}function up(){document.removeEventListener("pointermove",mv);document.removeEventListener("pointerup",up);clearGuides();saveWorkingLayout();renderAll()}document.addEventListener("pointermove",mv);document.addEventListener("pointerup",up)}
function snapRect(r,id){if(!$("snapToggle").checked)return{...r,guides:[]};const th=Number($("snapPx").value||5),b=labelBounds(),xs=[0,b.w/2,b.w],ys=[0,b.h/2,b.h];for(const[oid,o]of Object.entries(layout.objects)){if(oid===id||o.visible===false)continue;xs.push(o.x,o.x+o.w/2,o.x+o.w);ys.push(o.y,o.y+o.h/2,o.y+o.h)}const rx=[r.x,r.x+r.w/2,r.x+r.w],ry=[r.y,r.y+r.h/2,r.y+r.h],guides=[];let bx=null,bd=Infinity,bi=0;xs.forEach(xv=>rx.forEach((rv,i)=>{const d=Math.abs(rv-xv);if(d<bd&&d<=th){bd=d;bx=xv;bi=i}}));if(bx!==null){if(bi===0)r.x=bx;if(bi===1)r.x=bx-r.w/2;if(bi===2)r.x=bx-r.w;guides.push({type:"v",pos:bx})}let by=null,byd=Infinity,byi=0;ys.forEach(yv=>ry.forEach((rv,i)=>{const d=Math.abs(rv-yv);if(d<byd&&d<=th){byd=d;by=yv;byi=i}}));if(by!==null){if(byi===0)r.y=by;if(byi===1)r.y=by-r.h/2;if(byi===2)r.y=by-r.h;guides.push({type:"h",pos:by})}r.x=clamp(r.x,0,Math.max(0,b.w-r.w));r.y=clamp(r.y,0,Math.max(0,b.h-r.h));return{...r,guides}}
function drawGuides(gs=[]){clearGuides();const lab=document.querySelector(".label");if(!lab)return;for(const g of gs){const d=document.createElement("div");d.className="guide "+g.type;if(g.type==="v")d.style.left=g.pos+"px";else d.style.top=g.pos+"px";lab.appendChild(d)}}function clearGuides(){document.querySelectorAll(".guide").forEach(g=>g.remove())}
function clampObject(id){const o=layout.objects[id],b=labelBounds();o.w=clamp(Number(o.w||10),8,b.w);o.h=clamp(Number(o.h||10),8,b.h);o.x=clamp(Number(o.x||0),0,Math.max(0,b.w-o.w));o.y=clamp(Number(o.y||0),0,Math.max(0,b.h-o.h))}function clampAllObjects(){Object.keys(layout.objects).forEach(clampObject)}
function renderObjectPanel(){const h=$("objectPanel");h.innerHTML="";for(const id of["ITEM","WO","QR","WEEK"]){const o=layout.objects[id],b=document.createElement("button");b.className="objectBtn"+(selectedId===id?" active":"");b.innerHTML=`<span>${id}</span><span class="badge">${o.locked?"LOCKED":"UNLOCKED"}</span>`;b.onclick=()=>selectObject(id);h.appendChild(b)}}function selectObject(id){selectedId=id;renderObjectPanel();renderCanvas();syncControls()}
function syncControls(){const o=layout.objects[selectedId];if(!o)return;$("selectedName").textContent=selectedId;for(const k of["x","y","w","h","rot","fontSize"]){const inp=$(k);if(inp)inp.value=Math.round(Number(o[k]||0))}$("fontSize").disabled=selectedId==="QR";$("lockToggle").checked=!!o.locked;$("visibleToggle").checked=o.visible!==false;$("safeMargin").value=Number(layout.safeMarginPx||0);$("safeValue").textContent=Number(layout.safeMarginPx||0)+"px";$("gridPx").value=Number(layout.gridPx||4)}
function applyControls(){pushHistory();const o=layout.objects[selectedId];for(const k of["x","y","w","h","rot"]){const v=Number($(k).value);if(isFinite(v))o[k]=v}if(selectedId!=="QR"){const fs=Number($("fontSize").value);if(isFinite(fs)&&fs>0)o.fontSize=fs;o.fontFamily="Times New Roman"}o.locked=$("lockToggle").checked;o.visible=$("visibleToggle").checked;layout.safeMarginPx=Number($("safeMargin").value||0);layout.gridPx=Number($("gridPx").value||4);clampObject(selectedId);saveWorkingLayout();renderAll()}
function centerSelected(axis){pushHistory();const o=layout.objects[selectedId],b=labelBounds();if(axis==="h"||axis==="both")o.x=Math.round((b.w-o.w)/2);if(axis==="v"||axis==="both")o.y=Math.round((b.h-o.h)/2);saveWorkingLayout();renderAll()}
function renderRows(){const q=$("search").value.toLowerCase();filteredRows=rows.filter(r=>Object.values(r).join(" ").toLowerCase().includes(q));if(currentRowIndex>=filteredRows.length)currentRowIndex=0;const tb=$("rowsBody");tb.innerHTML="";filteredRows.slice(0,300).forEach((r,i)=>{const tr=document.createElement("tr");if(i===currentRowIndex)tr.className="active";tr.innerHTML=`<td>${cap(r.wo)}</td><td>${cap(r.act)}</td><td>${cap(r.scion||r.rootstock)}</td><td><button data-i="${i}">Add</button></td>`;tr.onclick=e=>{if(e.target.tagName==="BUTTON"){addToQueue(r);return}currentRowIndex=i;renderRows();renderCanvas()};tb.appendChild(tr)})}
function addToQueue(r=currentRow()){const id=Date.now()+"_"+Math.random().toString(16).slice(2);queue.push({id,row:clone(r),qty:Math.max(1,parseInt(r.labelsNeeded||"1",10)||1)});saveQueue();renderQueue()}
function saveQueue(){localStorage.setItem("beinvtPrintQueue",JSON.stringify(queue))}
function renderQueue(){const h=$("queueList");h.innerHTML="";if(!queue.length){h.innerHTML='<div class="small">Queue is empty.</div>';return}queue.forEach(q=>{const d=document.createElement("div");d.className="queueItem";d.innerHTML=`<div><b>${cap(q.row.wo)}</b><div class="small">${cap(q.row.scion||q.row.rootstock)}</div></div><input type="number" min="1" value="${q.qty}"><button class="danger">x</button>`;d.querySelector("input").onchange=e=>{q.qty=Math.max(1,parseInt(e.target.value||"1",10)||1);saveQueue()};d.querySelector("button").onclick=()=>{queue=queue.filter(x=>x.id!==q.id);saveQueue();renderQueue()};h.appendChild(d)})}
function renderPresetList(){const s=$("presetSelect"),names=Object.keys(presets).sort();s.innerHTML='<option value="">Select saved preset...</option>'+names.map(n=>`<option>${escapeHtml(n)}</option>`).join("")}
function savePreset(){const name=prompt("Preset name:",layout.name||`${labelType} Custom`);if(!name)return;layout.name=name;presets[name]=clone(layout);localStorage.setItem("beinvtLayoutPresets",JSON.stringify(presets));renderPresetList()}
function loadPreset(){const n=$("presetSelect").value;if(n&&presets[n])setLayout(presets[n])}function deletePreset(){const n=$("presetSelect").value;if(n&&confirm(`Delete preset "${n}"?`)){delete presets[n];localStorage.setItem("beinvtLayoutPresets",JSON.stringify(presets));renderPresetList()}}
function exportLayout(){$("layoutJson").value=JSON.stringify(layout,null,2)}function importLayout(){try{const obj=JSON.parse($("layoutJson").value);if(!obj.objects)throw Error("Layout missing objects");setLayout(obj)}catch(e){alert("Import failed: "+e.message)}}function downloadLayout(){const blob=new Blob([JSON.stringify(layout,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(layout.name||"label-layout").replace(/[^\w-]+/g,"_")+".json";a.click();URL.revokeObjectURL(a.href)}
function resetLayout(){if(confirm("Reset current label type?"))setLayout(DEFAULT_LAYOUTS[labelType]||fallbackLayout(labelType))}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function printCalibration(){const w=window.open("","_blank");w.document.write(`<!doctype html><style>@page{size:2in 2in;margin:0}body{margin:0}.sq{width:1in;height:1in;border:2px solid #000;margin:.25in;font:12px Arial;display:flex;align-items:center;justify-content:center}</style><div class="sq">1in x 1in</div><script>setTimeout(()=>print(),200)<\/script>`);w.document.close()}
function saveCalibration(){const mw=Number($("measuredW").value||1),mh=Number($("measuredH").value||1);if(mw>0&&mh>0){calibration={scaleX:1/mw,scaleY:1/mh};localStorage.setItem("beinvtCalibration",JSON.stringify(calibration));$("calStatus").textContent=`Saved: X ${calibration.scaleX.toFixed(4)}, Y ${calibration.scaleY.toFixed(4)}`}}
function printLabel(){printRows([{row:currentRow(),qty:1}])}function printQueue(){if(!queue.length){alert("Queue is empty.");return}printRows(queue)}
function printRows(items){const s=LABEL_SIZES[labelType],b=sizePx(),win=window.open("","_blank");let pages="";items.forEach(item=>{for(let i=0;i<Math.max(1,item.qty||1);i++)pages+=renderPrintPage(item.row,b)});win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Print Labels</title><style>@page{size:${s.widthIn}in ${s.heightIn}in;margin:0}html,body{margin:0;padding:0;background:#fff}.page{position:relative;width:${b.w}px;height:${b.h}px;overflow:hidden;background:#fff;color:#000;page-break-after:always;break-after:page;transform-origin:0 0;transform:scale(${calibration.scaleX},${calibration.scaleY})}*{box-sizing:border-box}</style></head><body>${pages}<script>setTimeout(()=>print(),300)<\/script></body></html>`);win.document.close()}
function renderPrintPage(row,b){let out=`<div class="page">`;for(const id of["ITEM","WO","QR","WEEK"]){const o=layout.objects[id];if(!o||o.visible===false)continue;const common=`position:absolute;left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px;transform:rotate(${o.rot||0}deg);transform-origin:center center;`;if(id==="QR")out+=`<img src="${qrUrl(row.wo)}" style="${common}image-rendering:pixelated"/>`;else{if(id==="WEEK"&&!row.week)continue;out+=`<div style="${common}display:flex;align-items:${alignV(o.alignV)};justify-content:${alignH(o.alignH)};overflow:hidden;text-align:center;white-space:nowrap;text-transform:uppercase;font-family:'Times New Roman',Georgia,serif;font-weight:900;font-size:${o.fontSize||16}px;line-height:.95;">${escapeHtml(labelText(id,row))}</div>`}}return out+"</div>"}
function initEvents(){$("labelType").onchange=e=>{labelType=e.target.value;selectedId="ITEM";undoStack=[];redoStack=[];setLayout(loadWorkingLayout(labelType),false)};$("zoom").oninput=renderCanvas;$("search").oninput=renderRows;$("safeToggle").onchange=e=>{showSafeZone=e.target.checked;renderCanvas()};$("gridToggle").onchange=e=>{showGrid=e.target.checked;renderCanvas()};$("gridPx").onchange=applyControls;$("safeMargin").oninput=e=>{layout.safeMarginPx=Number(e.target.value||0);$("safeValue").textContent=layout.safeMarginPx+"px";saveWorkingLayout();renderCanvas()};for(const id of["x","y","w","h","rot","fontSize"]){$(id).onchange=applyControls;$(id).onkeydown=e=>{if(e.key==="Enter")applyControls()}}$("lockToggle").onchange=applyControls;$("visibleToggle").onchange=applyControls;$("centerH").onclick=()=>centerSelected("h");$("centerV").onclick=()=>centerSelected("v");$("centerBoth").onclick=()=>centerSelected("both");$("savePreset").onclick=savePreset;$("loadPreset").onclick=loadPreset;$("deletePreset").onclick=deletePreset;$("exportLayout").onclick=exportLayout;$("importLayout").onclick=importLayout;$("downloadLayout").onclick=downloadLayout;$("resetLayout").onclick=resetLayout;$("printCalibration").onclick=printCalibration;$("saveCalibration").onclick=saveCalibration;$("testMode").onclick=()=>{testMode=!testMode;$("testMode").classList.toggle("good",testMode);renderCanvas()};$("printLabel").onclick=printLabel;$("printQueue").onclick=printQueue;$("addCurrent").onclick=()=>addToQueue();$("clearQueue").onclick=()=>{queue=[];saveQueue();renderQueue()};$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;document.addEventListener("keydown",e=>{const tag=document.activeElement.tagName;if(["INPUT","TEXTAREA","SELECT"].includes(tag))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();redo();return}const o=layout.objects[selectedId];if(!o||o.locked)return;let changed=false,step=e.shiftKey?10:1;if(e.key==="ArrowUp"){pushHistory();o.y-=step;changed=true}else if(e.key==="ArrowDown"){pushHistory();o.y+=step;changed=true}else if(e.key==="ArrowLeft"){pushHistory();o.x-=step;changed=true}else if(e.key==="ArrowRight"){pushHistory();o.x+=step;changed=true}if(changed){e.preventDefault();clampObject(selectedId);saveWorkingLayout();renderAll()}})}
function boot(){loadDefaults().then(()=>{layout=loadWorkingLayout(labelType);initEvents();loadCsv().catch(console.warn).finally(renderAll)})}
boot();
