name: Update label CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "7,22,37,52 * * * *"

permissions:
  contents: write

jobs:
  update-label-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download NetSuite CSV
        run: |
          mkdir -p data
          curl -L --fail --silent --show-error --retry 3 --retry-delay 5 \
            "https://11150895.app.netsuite.com/core/media/media.nl?id=153927&c=11150895&h=4FmNLpI0h4WxdsSTfd7WBBneTX9PXXjuYH5uGi9mK5ZjXntV&_xt=.csv" \
            -o data/labels.csv

          test -s data/labels.csv
          head -n 5 data/labels.csv

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/labels.csv

          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
          else
            git commit -m "Update label CSV"
            git push
          fi
